### ISSUE TITLE
Add Exception Handler

### ISSUE THREAD

**Issue by ckdarby** [EloGank/lol-replay-downloader-cli#2]
How do you feel about this? We have a need to override the game found exception to not throw an error. Was hoping to fork & add functionality similar to the success & failure handler.

**Comment by Divi** [comment]
I don't remember if the Symfony application throws an exception, but did you try to handle the exception in the `console` file, with a try/catch on the `$application->run()` ?

**Comment by ckdarby** [comment]
Sorry, my initial message was written in a rather rush. While the try/catch option would work, I would rather the option of not needing to modify the source code of the project altogether. It causes maintainability issues when pulling upstream down in the future.

The ideal situation was similar to the handler set up with [config.yml](https://github.com/EloGank/lol-replay-downloader-cli/blob/master/config/config.yml.dist)

It would along the lines of:

```YML

        exceptions:
            handler:
                # Override exception, must be a class namespace
                GameEndedException: ~
                # Override exception, must be a class namespace
                GameNotFoundException: ~
                # Override exception, must be a class namespace
                GameNotStartedException: ~
                # Override exception, must be a class namespace
                ReplayFolderAlreadyExistsException: \Ckdarby\Elogank\Exceptions\ReplayFolderAlreadyExistsException

```
